# Generated by Django 5.2.8 on 2025-11-06 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ilan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilan_no', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='İlan No')),
                ('emlak_tipi', models.CharField(choices=[('Daire', 'Satılık Daire'), ('Villa', 'Villa'), ('Arsa', 'Arsa'), ('İşyeri', 'İşyeri')], max_length=20, verbose_name='Emlak Tipi')),
                ('il', models.CharField(max_length=50)),
                ('ilce', models.CharField(max_length=50)),
                ('mahalle', models.CharField(max_length=100, verbose_name='Mahalle/Semt')),
                ('oda_sayisi', models.CharField(max_length=10, verbose_name='Oda Sayısı (Örn: 2+1)')),
                ('brut_alan', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Brüt Alan (m²)')),
                ('net_alan', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Net Alan (m²)')),
                ('bina_yasi', models.CharField(choices=[('0-5', '0-5 Yaşında'), ('6-10', '6-10 Yaşında'), ('11-15', '11-15 Yaşında'), ('16+', '16 Yaş ve Üzeri')], max_length=10, verbose_name='Bina Yaşı')),
                ('bulundugu_kat', models.IntegerField(verbose_name='Bulunduğu Kat')),
                ('kat_sayisi', models.IntegerField(verbose_name='Toplam Kat Sayısı')),
                ('banyo_sayisi', models.IntegerField(default=1, verbose_name='Banyo Sayısı')),
                ('mutfak', models.CharField(default='Ayrı', max_length=50, verbose_name='Mutfak Tipi')),
                ('krediye_uygun', models.BooleanField(default=False, verbose_name='Krediye Uygun')),
                ('site_icerisinde', models.BooleanField(default=False, verbose_name='Site İçerisinde')),
                ('site_adi', models.CharField(blank=True, max_length=100, null=True)),
                ('otopark', models.CharField(default='Yok', max_length=50, verbose_name='Otopark Tipi')),
                ('asansor', models.BooleanField(default=False)),
                ('balkon', models.BooleanField(default=False)),
                ('esyali', models.BooleanField(default=False, verbose_name='Eşyalı')),
                ('kullanım_durumu', models.CharField(default='Boş', max_length=20, verbose_name='Kullanım Durumu')),
                ('takas', models.BooleanField(default=False)),
                ('aidat_tl', models.IntegerField(blank=True, null=True, verbose_name='Aidat (TL)')),
                ('fiyat', models.BigIntegerField()),
                ('durum', models.CharField(choices=[('Aktif', 'Aktif'), ('Satıldı', 'Satıldı'), ('Kiralandı', 'Kiralandı'), ('Yayından Kaldırıldı', 'Yayından Kaldırıldı')], default='Aktif', max_length=25)),
                ('tapu_durumu', models.CharField(choices=[('Kat Mülkiyeti', 'Kat Mülkiyeti'), ('Kat İrtifaklı', 'Kat İrtifaklı'), ('Hisseli', 'Hisseli')], max_length=30, verbose_name='Tapu Durumu')),
                ('kayit_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='İlana Koyulma Tarihi')),
                ('son_guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Son Güncellenme Tarihi')),
                ('yayindan_kaldirma_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Yayından Kaldırma Tarihi')),
            ],
            options={
                'verbose_name': 'İlan',
                'verbose_name_plural': 'İlanlar',
            },
        ),
        migrations.CreateModel(
            name='Musteri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('talep_ozeti', models.TextField(verbose_name='Talep Özeti')),
                ('kayit_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Müşteri',
                'verbose_name_plural': 'Müşteriler',
            },
        ),
        migrations.CreateModel(
            name='Randevu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih_saat', models.DateTimeField()),
                ('notlar', models.TextField(blank=True, null=True)),
                ('durum', models.CharField(choices=[('Planlandı', 'Planlandı'), ('Tamamlandı', 'Tamamlandı'), ('İptal Edildi', 'İptal Edildi')], default='Planlandı', max_length=20)),
                ('ilan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='randevular', to='emlak.ilan')),
                ('ilgili_musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='randevular', to='emlak.musteri')),
            ],
            options={
                'verbose_name': 'Randevu',
                'verbose_name_plural': 'Randevular',
            },
        ),
        migrations.CreateModel(
            name='Sozlesme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sozlesme_no', models.CharField(max_length=50, unique=True, verbose_name='Sözleşme No')),
                ('sozlesme_tipi', models.CharField(choices=[('Satis', 'Satış Sözleşmesi'), ('Kira', 'Kira Sözleşmesi'), ('Hizmet', 'Hizmet Sözleşmesi'), ('Portfoy', 'Portföy Yetki Sözleşmesi')], max_length=20, verbose_name='Tip')),
                ('baslangic_tarihi', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('bitis_tarihi', models.DateField(blank=True, null=True, verbose_name='Bitiş Tarihi (Kira/Portföy)')),
                ('durum', models.CharField(choices=[('Aktif', 'Aktif'), ('Bitti', 'Süresi Bitti'), ('Iptal', 'İptal Edildi')], default='Aktif', max_length=10)),
                ('dosya_yolu', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dijital Dosya Yolu')),
                ('aciklama', models.TextField(blank=True, verbose_name='Ek Açıklamalar')),
                ('ilgili_ilan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sozlesmeler', to='emlak.ilan')),
                ('ilgili_musteri', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yaptigi_sozlesmeler', to='emlak.musteri')),
            ],
            options={
                'verbose_name': 'Sözleşme',
                'verbose_name_plural': 'Sözleşmeler',
            },
        ),
    ]
