# Generated by Django 5.2.7 on 2025-11-06 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emlak', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musteri',
            options={},
        ),
        migrations.RemoveField(
            model_name='sozlesme',
            name='ilgili_musteri',
        ),
        migrations.AddField(
            model_name='musteri',
            name='rol',
            field=models.CharField(choices=[('Satici', 'Satıcı / Mülk Sahibi'), ('Alici', 'Alıcı / Potansiyel Alıcı'), ('Kiraci', 'Kiracı'), ('Kiralayan', 'Kiralayan / Kiraya Veren'), ('Genel', 'Genel İlgilenen')], default='Genel', max_length=20, verbose_name='Müşteri Rolü'),
        ),
        migrations.AddField(
            model_name='sozlesme',
            name='depozito_tutari',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Depozito Tutarı (TL)'),
        ),
        migrations.AddField(
            model_name='sozlesme',
            name='karsi_taraf_musteri',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='karsi_taraf_sozlesmeleri', to='emlak.musteri', verbose_name='Alıcı/Kiracı/Karşı Taraf'),
        ),
        migrations.AddField(
            model_name='sozlesme',
            name='komisyon_orani',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Komisyon Oranı (%)'),
        ),
        migrations.AddField(
            model_name='sozlesme',
            name='komisyon_tutari',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Komisyon Tutarı (TL)'),
        ),
        migrations.AddField(
            model_name='sozlesme',
            name='sahip_musteri',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sahip_oldugu_sozlesmeler', to='emlak.musteri', verbose_name='Mülk Sahibi/Ana Taraf'),
        ),
        migrations.AlterField(
            model_name='sozlesme',
            name='ilgili_ilan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sozlesmeler', to='emlak.ilan', verbose_name='İlgili İlan'),
        ),
    ]
