# Generated by Django 5.2.8 on 2025-11-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emlak", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ilan",
            name="isitma",
            field=models.CharField(
                choices=[
                    ("Dogalgaz_Kombi", "Doğalgaz (Kombi)"),
                    ("Merkezi_Payolcer", "Merkezi (Pay Ölçer)"),
                    ("Merkezi", "Merkezi"),
                    ("Klima", "Klima"),
                    ("Soba", "Soba"),
                ],
                default="Yok",
                max_length=30,
                verbose_name="Isıtma Tipi",
            ),
        ),
    ]
