# Generated by Django 5.2.8 on 2025-11-08 08:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emlak", "0002_ilan_isitma"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ilan",
            name="kayit_tarihi",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Kayıt Tarihi"
            ),
        ),
    ]
