# Generated by Django 5.2.7 on 2025-11-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emlak', '0002_alter_musteri_options_remove_sozlesme_ilgili_musteri_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sozlesme',
            name='dosya_yolu',
        ),
        migrations.AddField(
            model_name='sozlesme',
            name='dosya',
            field=models.FileField(blank=True, null=True, upload_to='sozlesme_belgeleri/', verbose_name='Sözleşme Dosyası (PDF/DOCX)'),
        ),
    ]
