# Generated by Django 5.2.8 on 2025-11-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emlak", "0003_alter_ilan_kayit_tarihi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ilan",
            name="mutfak",
            field=models.CharField(
                choices=[
                    ("Kapali", "Kapalı Mutfak"),
                    ("Amerikan", "Amerikan Mutfak"),
                    ("Yari_Acik", "Yarı Açık Mutfak"),
                ],
                default="Kapali",
                max_length=30,
                verbose_name="Mutfak Tipi",
            ),
        ),
        migrations.AlterField(
            model_name="ilan",
            name="otopark",
            field=models.CharField(
                choices=[
                    ("Yok", "Yok"),
                    ("Acik", "Açık Otopark"),
                    ("Kapali", "Kapalı Otopark"),
                    ("Acik_Kapali", "Açık ve Kapalı"),
                ],
                default="Yok",
                max_length=30,
                verbose_name="Otopark",
            ),
        ),
    ]
