# Generated by Django 5.2.7 on 2025-11-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emlak', '0003_remove_sozlesme_dosya_yolu_sozlesme_dosya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilan',
            name='emlak_tipi',
            field=models.CharField(choices=[('Satilik Daire', 'Satılık Daire'), ('Satilik Villa', 'Satılık Villa'), ('Satilik Arsa', 'Satılık Arsa'), ('Satilik İşyeri', 'Satılık İşyeri'), ('Kiralik Daire', 'Kiralık Daire'), ('Kiralik Villa', 'Kiralık Villa'), ('Kiralik İşyeri', 'Kiralık İşyeri')], max_length=20, verbose_name='Emlak Tipi'),
        ),
    ]
