# Generated by Django 5.2.7 on 2025-11-06 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emlak', '0004_alter_ilan_emlak_tipi'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilan',
            name='mulk_sahibi',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'satici'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ilanlarim', to='emlak.musteri', verbose_name='Mülk Sahibi'),
        ),
        migrations.AlterField(
            model_name='ilan',
            name='oda_sayisi',
            field=models.CharField(max_length=10, verbose_name='Oda Sayısı'),
        ),
    ]
