# Generated by Django 5.2.8 on 2025-11-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emlak", "0004_alter_ilan_mutfak_alter_ilan_otopark"),
    ]

    operations = [
        migrations.AddField(
            model_name="ilan",
            name="tam_adres",
            field=models.TextField(
                blank=True, null=True, verbose_name="Tam Adres/Sokak/Bina No"
            ),
        ),
    ]
