# Generated by Django 5.2.7 on 2025-11-06 17:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emlak', '0005_ilan_mulk_sahibi_alter_ilan_oda_sayisi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musteri',
            options={'verbose_name': 'Müşteri', 'verbose_name_plural': 'Müşteriler'},
        ),
        migrations.AddField(
            model_name='musteri',
            name='olusturulma_tarihi',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Oluşturulma Tarihi'),
        ),
    ]
