# Generated by Django 5.2.8 on 2025-11-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emlak", "0005_ilan_tam_adres"),
    ]

    operations = [
        migrations.AddField(
            model_name="ilan",
            name="ada_no",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Ada No"
            ),
        ),
        migrations.AddField(
            model_name="ilan",
            name="gabari",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Gabari"
            ),
        ),
        migrations.AddField(
            model_name="ilan",
            name="imar_durumu",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="İmar Durumu"
            ),
        ),
        migrations.AddField(
            model_name="ilan",
            name="kaks_emsal",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Kaks (Emsal)"
            ),
        ),
        migrations.AddField(
            model_name="ilan",
            name="pafta_no",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Pafta No"
            ),
        ),
        migrations.AddField(
            model_name="ilan",
            name="parsel_no",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Parsel No"
            ),
        ),
    ]
