# Generated by Django 5.2.8 on 2025-11-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emlak", "0006_ilan_ada_no_ilan_gabari_ilan_imar_durumu_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ilan",
            name="emlak_tipi",
            field=models.CharField(
                choices=[
                    ("Satilik_Daire", "Satılık Daire"),
                    ("Satilik_Villa", "Satılık Villa"),
                    ("Satilik_Arsa", "Satılık Arsa"),
                    ("Satilik_Isyeri", "Satılık İşyeri"),
                    ("Kiralik_Daire", "Kiralık Daire"),
                    ("Kiralik_Villa", "Kiralık Villa"),
                    ("Kiralik_Isyeri", "Kiralık İşyeri"),
                ],
                max_length=20,
                verbose_name="Emlak Tipi",
            ),
        ),
    ]
