# Generated by Django 5.2.8 on 2025-11-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emlak", "0007_alter_ilan_emlak_tipi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ilan",
            name="kat_sayisi",
            field=models.CharField(
                choices=[
                    ("HEPSI", "Hepsi"),
                    ("1", "1"),
                    ("2", "2"),
                    ("3", "3"),
                    ("4", "4"),
                    ("5", "5"),
                    ("6", "6"),
                    ("7", "7"),
                    ("8", "8"),
                    ("9", "9"),
                    ("10", "10"),
                    ("11", "11"),
                    ("12", "12"),
                    ("13", "13"),
                    ("14", "14"),
                    ("15", "15"),
                    ("16", "16"),
                    ("17", "17"),
                    ("18", "18"),
                    ("19", "19"),
                    ("20", "20"),
                    ("21", "21"),
                    ("22", "22"),
                    ("23", "23"),
                    ("24", "24"),
                    ("25", "25"),
                    ("26", "26"),
                    ("27", "27"),
                    ("28", "28"),
                    ("29", "29"),
                ],
                default="HEPSI",
                max_length=5,
                verbose_name="Toplam Kat Sayısı",
            ),
        ),
    ]
