# Generated by Django 5.2.8 on 2025-11-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emlak", "0011_alter_ilan_bulundugu_kat_alter_ilan_kat_sayisi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ilan",
            name="emlak_tipi",
            field=models.CharField(
                choices=[
                    ("Satilik_Daire", "Satılık Daire"),
                    ("Satilik_Villa", "Satılık Villa"),
                    ("Satilik Mustakil Ev", "Satılık Müstakil Ev"),
                    ("Satilik_Arsa", "Satılık Arsa"),
                    ("Satilik_Isyeri", "Satılık İşyeri"),
                    ("Kiralik_Daire", "Kiralık Daire"),
                    ("Kiralik_Villa", "Kiralık Villa"),
                    ("Kiralik Mustakil Ev", "Kiralık Müstakil Ev"),
                    ("Kiralik_Isyeri", "Kiralık İşyeri"),
                ],
                max_length=20,
                verbose_name="Emlak Tipi",
            ),
        ),
    ]
