# Generated by Django 5.2.8 on 2025-11-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emlak", "0013_alter_ilan_emlak_tipi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ilan",
            name="emlak_tipi",
            field=models.CharField(
                choices=[
                    ("Satilik_Daire", "Satılık Daire"),
                    ("Satilik_Villa", "Satılık Villa"),
                    ("Satilik Mustakil Ev", "Satılık Müstakil Ev"),
                    ("Satilik_Arsa", "Satılık Arsa"),
                    ("Satilik_Isyeri", "Satılık İşyeri"),
                    ("Devren_Satilik_Isyeri", "Devren Satılık İş Yeri"),
                    ("Kiralik_Daire", "Kiralık Daire"),
                    ("Kiralik_Villa", "Kiralık Villa"),
                    ("Kiralik_Mustakil_Ev", "Kiralık Müstakil Ev"),
                    ("Kiralik_Isyeri", "Kiralık İşyeri"),
                    ("Devren_Kiralik_Isyeri", "Devren Kiralık İş Yeri"),
                ],
                max_length=30,
                verbose_name="Emlak Tipi",
            ),
        ),
    ]
