# Generated by Django 5.2.8 on 2025-11-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emlak", "0014_alter_ilan_emlak_tipi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ilan",
            name="oda_sayisi",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1+0", "1+0 Stüdyo"),
                    ("1+1", "1+1"),
                    ("2+1", "2+1"),
                    ("3+1", "3+1"),
                    ("4+1", "4+1"),
                    ("5+1", "5+1 ve Üzeri"),
                    ("5+", "5 ve Üzeri Odalı"),
                    ("Acik", "Açık Alan/Bölümsüz"),
                ],
                max_length=10,
                null=True,
                verbose_name="Oda Sayısı",
            ),
        ),
    ]
