# Generated by Django 5.2.8 on 2025-11-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emlak", "0018_alter_ilan_durum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ilan",
            name="durum",
            field=models.CharField(
                choices=[
                    ("aktif", "Aktif"),
                    ("satildi", "Satıldı"),
                    ("kiralandi", "Kiralandı"),
                    ("yayindan_kaldirildi", "Yayından Kaldırıldı"),
                ],
                default="Aktif",
                max_length=25,
            ),
        ),
    ]
